# library(shiny)
#
# # Annahme: bird_data ist ein Datenrahmen mit den Spalten "Vogel" und "Link"
# bird_data <- data.frame(
#   Vogel = c(
#     "Amandava amandava_Red Avadavat",
#     "Anas acuta_Northern Pintail",
#     "Anas crecca_Green-winged Teal",
#     "Anas platyrhynchos_Mallard",
#     "Anous minutus_Black Noddy",
#     "Anous stolidus_Brown Noddy",
#     "Anser albifrons_Greater White-fronted Goose",
#     "Anser caerulescens_Snow Goose",
#     "Ardea herodias_Great Blue Heron",
#     "Ardenna grisea_Sooty Shearwater",
#     "Ardenna pacifica_Wedge-tailed Shearwater",
#     "Ardenna tenuirostris_Short-tailed Shearwater",
#     "Arenaria interpres_Ruddy Turnstone",
#     "Asio flammeus_Short-eared Owl",
#     "Aythya affinis_Lesser Scaup",
#     "Aythya collaris_Ring-necked Duck",
#     "Aythya marila_Greater Scaup",
#     "Aythya valisineria_Canvasback",
#     "Branta bernicla_Brant",
#     "Branta canadensis_Canada Goose",
#     "Branta hutchinsii_Cackling Goose",
#     "Branta sandvicensis_Hawaiian Goose",
#     "Bubulcus ibis_Cattle Egret",
#     "Bucephala albeola_Bufflehead",
#     "Bulweria bulwerii_Bulwer's Petrel",
#     "Buteo solitarius_Hawaiian Hawk",
#     "Calidris acuminata_Sharp-tailed Sandpiper",
#     "Calidris alba_Sanderling",
#     "Calidris alpina_Dunlin",
#     "Calidris mauri_Western Sandpiper",
#     "Calidris melanotos_Pectoral Sandpiper",
#     "Calidris minutilla_Least Sandpiper",
#     "Calidris pugnax_Ruff",
#     "Calidris subruficollis_Buff-breasted Sandpiper",
#     "Callipepla californica_California Quail",
#     "Callipepla gambelii_Gambel's Quail",
#     "Cardinalis cardinalis_Northern Cardinal",
#     "Charadrius semipalmatus_Semipalmated Plover",
#     "Chasiempis sandwichensis_Hawaii Elepaio",
#     "Chlorodrepanis virens_Hawaii Amakihi",
#     "Chroicocephalus philadelphia_Bonaparte's Gull",
#     "Chrysolophus pictus_Golden Pheasant",
#     "Circus hudsonius_Northern Harrier",
#     "Columba livia_Rock Pigeon",
#     "Corvus hawaiiensis_Hawaiian Crow",
#     "Coturnix japonica_Japanese Quail",
#     "Crithagra mozambica_Yellow-fronted Canary",
#     "Cyanoliseus patagonus_Burrowing Parakeet",
#     "Drepanis coccinea_Iiwi",
#     "Estrilda astrild_Common Waxbill",
#     "Euodice cantans_African Silverbill",
#     "Falco columbarius_Merlin",
#     "Falco peregrinus_Peregrine Falcon",
#     "Francolinus francolinus_Black Francolin",
#     "Fregata minor_Great Frigatebird",
#     "Fulica alai_Hawaiian Coot",
#     "Gallinula galeata_Common Gallinule",
#     "Gallus gallus_Red Junglefowl",
#     "Garrulax canorus_Chinese Hwamei",
#     "Geopelia striata_Zebra Dove",
#     "Glaucestrilda caerulescens_Lavender Waxbill",
#     "Gygis alba_White Tern",
#     "Haemorhous mexicanus_House Finch",
#     "Hemignathus wilsoni_Akiapolaau",
#     "Himantopus mexicanus_Black-necked Stilt",
#     "Himatione sanguinea_Apapane",
#     "Horornis diphone_Japanese Bush Warbler",
#     "Hydrobates castro_Band-rumped Storm-Petrel",
#     "Hydrobates leucorhous_Leach's Storm-Petrel",
#     "Hydroprogne caspia_Caspian Tern",
#     "Larosterna inca_Inca Tern",
#     "Larus delawarensis_Ring-billed Gull",
#     "Larus glaucescens_Glaucous-winged Gull",
#     "Leiothrix lutea_Red-billed Leiothrix",
#     "Leucophaeus atricilla_Laughing Gull",
#     "Leucophaeus pipixcan_Franklin's Gull",
#     "Limnodromus scolopaceus_Long-billed Dowitcher",
#     "Limosa haemastica_Hudsonian Godwit",
#     "Lonchura atricapilla_Chestnut Munia",
#     "Lonchura punctulata_Scaly-breasted Munia",
#     "Lophodytes cucullatus_Hooded Merganser",
#     "Lophura leucomelanos_Kalij Pheasant",
#     "Loxioides bailleui_Palila",
#     "Loxops caeruleirostris_Akekee",
#     "Loxops coccineus_Hawaii Akepa",
#     "Loxops mana_Hawaii Creeper",
#     "Mareca americana_American Wigeon",
#     "Mareca penelope_Eurasian Wigeon",
#     "Mareca strepera_Gadwall",
#     "Megaceryle alcyon_Belted Kingfisher",
#     "Meleagris gallopavo_Wild Turkey",
#     "Mimus polyglottos_Northern Mockingbird",
#     "Myadestes obscurus_Omao",
#     "Myadestes palmeri_Puaiohi",
#     "Numenius tahitiensis_Bristle-thighed Curlew",
#     "Nycticorax nycticorax_Black-crowned Night-Heron",
#     "Onychoprion fuscatus_Sooty Tern",
#     "Onychoprion lunatus_Gray-backed Tern",
#     "Oreomystis bairdi_Akikiki",
#     "Ortygornis pondicerianus_Gray Francolin",
#     "Padda oryzivora_Java Sparrow",
#     "Palmeria dolei_Akohekohe",
#     "Pandion haliaetus_Osprey",
#     "Paroaria capitata_Yellow-billed Cardinal",
#     "Paroaria coronata_Red-crested Cardinal",
#     "Paroreomyza montana_Maui Alauahio",
#     "Passer domesticus_House Sparrow",
#     "Pavo cristatus_Indian Peafowl",
#     "Phaethon lepturus_White-tailed Tropicbird",
#     "Phaethon rubricauda_Red-tailed Tropicbird",
#     "Phalaropus fulicarius_Red Phalarope",
#     "Phasianus colchicus_Ring-necked Pheasant",
#     "Phoebastria immutabilis_Laysan Albatross",
#     "Phoebastria nigripes_Black-footed Albatross",
#     "Plegadis chihi_White-faced Ibis",
#     "Pluvialis fulva_Pacific Golden-Plover",
#     "Pluvialis squatarola_Black-bellied Plover",
#     "Podilymbus podiceps_Pied-billed Grebe",
#     "Porzana carolina_Sora",
#     "Pseudonestor xanthophrys_Maui Parrotbill",
#     "Psittacara erythrogenys_Red-masked Parakeet",
#     "Psittacara mitratus_Mitred Parakeet",
#     "Psittacula krameri_Rose-ringed Parakeet",
#     "Pternistis erckelii_Erckel's Francolin",
#     "Pterocles exustus_Chestnut-bellied Sandgrouse",
#     "Pterodroma cookii_Cook's Petrel",
#     "Pterodroma externa_Juan Fernandez Petrel",
#     "Pterodroma inexpectata_Mottled Petrel",
#     "Pterodroma neglecta_Kermadec Petrel",
#     "Pterodroma nigripennis_Black-winged Petrel",
#     "Pterodroma sandwichensis_Hawaiian Petrel",
#     "Puffinus nativitatis_Christmas Shearwater",
#     "Puffinus newelli_Newell's Shearwater",
#     "Sicalis flaveola_Saffron Finch",
#     "Spatula clypeata_Northern Shoveler",
#     "Spatula cyanoptera_Cinnamon Teal",
#     "Spatula discors_Blue-winged Teal",
#     "Stercorarius longicaudus_Long-tailed Jaeger",
#     "Stercorarius maccormicki_South Polar Skua",
#     "Stercorarius parasiticus_Parasitic Jaeger",
#     "Stercorarius pomarinus_Pomarine Jaeger",
#     "Sterna paradisaea_Arctic Tern",
#     "Sternula antillarum_Least Tern",
#     "Streptopelia chinensis_Spotted Dove",
#     "Sturnella neglecta_Western Meadowlark",
#     "Sula dactylatra_Masked Booby",
#     "Sula leucogaster_Brown Booby",
#     "Sula sula_Red-footed Booby",
#     "Tringa flavipes_Lesser Yellowlegs",
#     "Tringa incana_Wandering Tattler",
#     "Tyto alba_Barn Owl",
#     "Zenaida macroura_Mourning Dove",
#     "Zosterops japonicus_Warbling White-eye"
#   ),
#   Link = c(
#     "https://en.wikipedia.org/wiki/Red_avadavat",
#     "https://en.wikipedia.org/wiki/Northern_pintail",
#     "https://en.wikipedia.org/wiki/Green-winged_teal",
#     "https://en.wikipedia.org/wiki/Mallard",
#     "https://en.wikipedia.org/wiki/Black_noddy",
#     "https://en.wikipedia.org/wiki/Brown_noddy",
#     "https://en.wikipedia.org/wiki/Greater_white-fronted_goose",
#     "https://en.wikipedia.org/wiki/Snow_goose",
#     "https://en.wikipedia.org/wiki/Great_blue_heron",
#     "https://en.wikipedia.org/wiki/Sooty_shearwater",
#     "https://en.wikipedia.org/wiki/Wedge-tailed_shearwater",
#     "https://en.wikipedia.org/wiki/Short-tailed_shearwater",
#     "https://en.wikipedia.org/wiki/Ruddy_turnstone",
#     "https://en.wikipedia.org/wiki/Short-eared_owl",
#     "https://en.wikipedia.org/wiki/Lesser_scaup",
#     "https://en.wikipedia.org/wiki/Ring-necked_duck",
#     "https://en.wikipedia.org/wiki/Greater_scaup",
#     "https://en.wikipedia.org/wiki/Canvasback",
#     "https://en.wikipedia.org/wiki/Brant",
#     "https://en.wikipedia.org/wiki/Canada_goose",
#     "https://en.wikipedia.org/wiki/Cackling_goose",
#     "https://en.wikipedia.org/wiki/Hawaiian_goose",
#     "https://en.wikipedia.org/wiki/Cattle_egret",
#     "https://en.wikipedia.org/wiki/Bufflehead",
#     "https://en.wikipedia.org/wiki/Bulwer%27s_petrel",
#     "https://en.wikipedia.org/wiki/Hawaiian_hawk",
#     "https://en.wikipedia.org/wiki/Sharp-tailed_sandpiper",
#     "https://en.wikipedia.org/wiki/Sanderling",
#     "https://en.wikipedia.org/wiki/Dunlin",
#     "https://en.wikipedia.org/wiki/Western_sandpiper",
#     "https://en.wikipedia.org/wiki/Pectoral_sandpiper",
#     "https://en.wikipedia.org/wiki/Least_sandpiper",
#     "https://en.wikipedia.org/wiki/Ruff",
#     "https://en.wikipedia.org/wiki/Buff-breasted_sandpiper",
#     "https://en.wikipedia.org/wiki/California_quail",
#     "https://en.wikipedia.org/wiki/Gambel%27s_quail",
#     "https://en.wikipedia.org/wiki/Northern_cardinal",
#     "https://en.wikipedia.org/wiki/Semipalmated_plover",
#     "https://en.wikipedia.org/wiki/Hawaii_Elepaio",
#     "https://en.wikipedia.org/wiki/Hawaii_Amakihi",
#     "https://en.wikipedia.org/wiki/Bonaparte%27s_Gull",
#     "https://en.wikipedia.org/wiki/Golden_Pheasant",
#     "https://en.wikipedia.org/wiki/Northern_Harrier",
#     "https://en.wikipedia.org/wiki/Rock_Pigeon",
#     "https://en.wikipedia.org/wiki/Hawaiian_Crow",
#     "https://en.wikipedia.org/wiki/Japanese_Quail",
#     "https://en.wikipedia.org/wiki/Yellow-fronted_Canary",
#     "https://en.wikipedia.org/wiki/Burrowing_Parakeet",
#     "https://en.wikipedia.org/wiki/Iiwi",
#     "https://en.wikipedia.org/wiki/Common_Waxbill",
#     "https://en.wikipedia.org/wiki/African_Silverbill",
#     "https://en.wikipedia.org/wiki/Merlin_(bird)",
#     "https://en.wikipedia.org/wiki/Peregrine_Falcon",
#     "https://en.wikipedia.org/wiki/Black_Francolin",
#     "https://en.wikipedia.org/wiki/Great_Frigatebird",
#     "https://en.wikipedia.org/wiki/Hawaiian_Coot",
#     "https://en.wikipedia.org/wiki/Common_Gallinule",
#     "https://en.wikipedia.org/wiki/Red_Junglefowl",
#     "https://en.wikipedia.org/wiki/Chinese_Hwamei",
#     "https://en.wikipedia.org/wiki/Zebra_Dove",
#     "https://en.wikipedia.org/wiki/Lavender_Waxbill",
#     "https://en.wikipedia.org/wiki/White_Tern",
#     "https://en.wikipedia.org/wiki/House_Finch",
#     "https://en.wikipedia.org/wiki/Akiapolaau",
#     "https://en.wikipedia.org/wiki/Black-necked_Stilt",
#     "https://en.wikipedia.org/wiki/Apapane",
#     "https://en.wikipedia.org/wiki/Japanese_Bush_Warbler",
#     "https://en.wikipedia.org/wiki/Band-rumped_Storm-Petrel",
#     "https://en.wikipedia.org/wiki/Leach%27s_Storm-Petrel",
#     "https://en.wikipedia.org/wiki/Caspian_Tern",
#     "https://en.wikipedia.org/wiki/Inca_Tern",
#     "https://en.wikipedia.org/wiki/Ring-billed_Gull",
#     "https://en.wikipedia.org/wiki/Glaucous-winged_Gull",
#     "https://en.wikipedia.org/wiki/Red-billed_Leiothrix",
#     "https://en.wikipedia.org/wiki/Laughing_Gull",
#     "https://en.wikipedia.org/wiki/Franklin%27s_Gull",
#     "https://en.wikipedia.org/wiki/Long-billed_Dowitcher",
#     "https://en.wikipedia.org/wiki/Hudsonian_Godwit",
#     "https://en.wikipedia.org/wiki/Chestnut_Munia",
#     "https://en.wikipedia.org/wiki/Scaly-breasted_Munia",
#     "https://en.wikipedia.org/wiki/Hooded_Merganser",
#     "https://en.wikipedia.org/wiki/Kalij_Pheasant",
#     "https://en.wikipedia.org/wiki/Palila",
#     "https://en.wikipedia.org/wiki/Akekee",
#     "https://en.wikipedia.org/wiki/Hawaii_Akepa",
#     "https://en.wikipedia.org/wiki/Hawaii_Creeper",
#     "https://en.wikipedia.org/wiki/American_Wigeon",
#     "https://en.wikipedia.org/wiki/Eurasian_Wigeon",
#     "https://en.wikipedia.org/wiki/Gadwall",
#     "https://en.wikipedia.org/wiki/Belted_Kingfisher",
#     "https://en.wikipedia.org/wiki/Wild_Turkey",
#     "https://en.wikipedia.org/wiki/Northern_Mockingbird",
#     "https://en.wikipedia.org/wiki/Omao",
#     "https://en.wikipedia.org/wiki/Puaiohi",
#     "https://en.wikipedia.org/wiki/Bristle-thighed_Curlew",
#     "https://en.wikipedia.org/wiki/Black-crowned_Night-Heron",
#     "https://en.wikipedia.org/wiki/Sooty_Tern",
#     "https://en.wikipedia.org/wiki/Gray-backed_Tern",
#     "https://en.wikipedia.org/wiki/Akikiki",
#     "https://en.wikipedia.org/wiki/Gray_Francolin",
#     "https://en.wikipedia.org/wiki/Java_Sparrow",
#     "https://en.wikipedia.org/wiki/Akohekohe",
#     "https://en.wikipedia.org/wiki/Osprey",
#     "https://en.wikipedia.org/wiki/Yellow-billed_Cardinal",
#     "https://en.wikipedia.org/wiki/Red-crested_Cardinal",
#     "https://en.wikipedia.org/wiki/Maui_Alauahio",
#     "https://en.wikipedia.org/wiki/House_Sparrow",
#     "https://en.wikipedia.org/wiki/Indian_Peafowl",
#     "https://en.wikipedia.org/wiki/White-tailed_Tropicbird",
#     "https://en.wikipedia.org/wiki/Red-tailed_Tropicbird",
#     "https://en.wikipedia.org/wiki/Red_Phalarope",
#     "https://en.wikipedia.org/wiki/Ring-necked_Pheasant",
#     "https://en.wikipedia.org/wiki/Laysan_Albatross",
#     "https://en.wikipedia.org/wiki/Black-footed_Albatross",
#     "https://en.wikipedia.org/wiki/White-faced_Ibis",
#     "https://en.wikipedia.org/wiki/Pacific_Golden-Plover",
#     "https://en.wikipedia.org/wiki/Black-bellied_Plover",
#     "https://en.wikipedia.org/wiki/Pied-billed_Grebe",
#     "https://en.wikipedia.org/wiki/Sora",
#     "https://en.wikipedia.org/wiki/Maui_Parrotbill",
#     "https://en.wikipedia.org/wiki/Red-masked_Parakeet",
#     "https://en.wikipedia.org/wiki/Mitred_Parakeet",
#     "https://en.wikipedia.org/wiki/Rose-ringed_Parakeet",
#     "https://en.wikipedia.org/wiki/Erckel%27s_Francolin",
#     "https://en.wikipedia.org/wiki/Chestnut-bellied_Sandgrouse",
#     "https://en.wikipedia.org/wiki/Cook%27s_Petrel",
#     "https://en.wikipedia.org/wiki/Juan_Fernandez_Petrel",
#     "https://en.wikipedia.org/wiki/Mottled_Petrel",
#     "https://en.wikipedia.org/wiki/Kermadec_Petrel",
#     "https://en.wikipedia.org/wiki/Black-winged_Petrel",
#     "https://en.wikipedia.org/wiki/Hawaiian_Petrel",
#     "https://en.wikipedia.org/wiki/Christmas_Shearwater",
#     "https://en.wikipedia.org/wiki/Newell%27s_Shearwater",
#     "https://en.wikipedia.org/wiki/Saffron_Finch",
#     "https://en.wikipedia.org/wiki/Northern_Shoveler",
#     "https://en.wikipedia.org/wiki/Cinnamon_Teal",
#     "https://en.wikipedia.org/wiki/Blue-winged_Teal",
#     "https://en.wikipedia.org/wiki/Long-tailed_Jaeger",
#     "https://en.wikipedia.org/wiki/South_Polar_Skua",
#     "https://en.wikipedia.org/wiki/Parasitic_Jaeger",
#     "https://en.wikipedia.org/wiki/Pomarine_Jaeger",
#     "https://en.wikipedia.org/wiki/Arctic_Tern",
#     "https://en.wikipedia.org/wiki/Least_Tern",
#     "https://en.wikipedia.org/wiki/Spotted_Dove",
#     "https://en.wikipedia.org/wiki/Western_Meadowlark",
#     "https://en.wikipedia.org/wiki/Masked_Booby",
#     "https://en.wikipedia.org/wiki/Brown_Booby",
#     "https://en.wikipedia.org/wiki/Red-footed_Booby",
#     "https://en.wikipedia.org/wiki/Lesser_Yellowlegs",
#     "https://en.wikipedia.org/wiki/Wandering_Tattler",
#     "https://en.wikipedia.org/wiki/Barn_Owl",
#     "https://en.wikipedia.org/wiki/Mourning_Dove",
#     "https://en.wikipedia.org/wiki/Warbling_White-eye"))
#
# ui <- fluidPage(
#   titlePanel("Vogel-Wikipedia-Verknüpfung"),
#   sidebarLayout(
#     sidebarPanel(
#       selectInput("vogel", "Vogel auswählen", choices = unique(bird_data$Vogel)),
#       actionButton("openPage", "Wikipedia-Seite öffnen")
#       #was kltzt du schon wieder :D willst nicht mal selbst programmieren :D lser
#       #was kltzt du schon wieder :D willst nicht mal selbst programmieren :D lser
#       #was kltzt du schon wieder :D willst nicht mal selbst programmieren :D lser
#     ),
#     mainPanel(
#       uiOutput("wikipediaLink")
#     )
#   )
# )
#
# server <- function(input, output, session) {
#   output$wikipediaLink <- renderUI({
#     if (!is.null(input$openPage)) {
#       selectedVogel <- input$vogel
#       # Überprüfe, ob der ausgewählte Vogel in der Datenquelle vorhanden ist
#       if (selectedVogel %in% bird_data$Vogel) {
#         selectedLink <- bird_data$Link[bird_data$Vogel == selectedVogel]
#         tags$a(href = selectedLink, "Wikipedia-Seite öffnen")
#       } else {
#         "Vogel nicht gefunden. Wählen Sie einen anderen Vogel aus."
#       }
#     } else {
#       "Wählen Sie einen Vogel aus und klicken Sie auf 'Wikipedia-Seite öffnen'."
#     }
#   })
# }
#
# shinyApp(ui, server)
