library(shiny)


ui <- fluidPage(
  titlePanel("Vogel-Wikipedia-Verknüpfung"),
  sidebarLayout(
    sidebarPanel(
      selectInput("vogel", "Vogel auswählen", choices = unique(bird_data$Vogel)),
      actionButton("openPage", "Wikipedia-Seite öffnen")
    ),
    mainPanel(
      uiOutput("wikipediaLink")
    )
  )
)

server <- function(input, output, session) {
  output$wikipediaLink <- renderUI({
    if (!is.null(input$openPage)) {
      selectedVogel <- input$vogel
      selectedBird <- unlist(strsplit(selectedVogel, ","))[[1]]  # Extract the bird name
      # Find the Wikipedia link for the selected bird
      selectedLink <- switch(selectedBird,
                             "Amandava amandava_Red Avadavat" = "https://en.wikipedia.org/wiki/Red_avadavat",
                             "Anas acuta_Northern Pintail" = "https://en.wikipedia.org/wiki/Northern_pintail",
                             "Anas crecca_Green-winged Teal" = "https://en.wikipedia.org/wiki/Green-winged_teal",
                             "Anas platyrhynchos_Mallard" = "https://en.wikipedia.org/wiki/Mallard",
                             "Anous minutus_Black Noddy" = "https://en.wikipedia.org/wiki/Black_noddy",
                             "Anous stolidus_Brown Noddy" = "https://en.wikipedia.org/wiki/Brown_noddy",
                             "Anser albifrons_Greater White-fronted Goose" = "https://en.wikipedia.org/wiki/Greater_white-fronted_goose",
                             "Anser caerulescens_Snow Goose" = "https://en.wikipedia.org/wiki/Snow_goose",
                             "Ardea herodias_Great Blue Heron" = "https://en.wikipedia.org/wiki/Great_blue_heron",
                             "Ardenna grisea_Sooty Shearwater" = "https://en.wikipedia.org/wiki/Sooty_shearwater",
                             "Ardenna pacifica_Wedge-tailed Shearwater" = "https://en.wikipedia.org/wiki/Wedge-tailed_shearwater",
                             "Ardenna tenuirostris_Short-tailed Shearwater" = "https://en.wikipedia.org/wiki/Short-tailed_shearwater",
                             "Arenaria interpres_Ruddy Turnstone" = "https://en.wikipedia.org/wiki/Ruddy_turnstone",
                             "Asio flammeus_Short-eared Owl" = "https://en.wikipedia.org/wiki/Short-eared_owl",
                             "Aythya affinis_Lesser Scaup" = "https://en.wikipedia.org/wiki/Lesser_scaup",
                             "Aythya collaris_Ring-necked Duck" = "https://en.wikipedia.org/wiki/Ring-necked_duck",
                             "Aythya marila_Greater Scaup" = "https://en.wikipedia.org/wiki/Greater_scaup",
                             "Aythya valisineria_Canvasback" = "https://en.wikipedia.org/wiki/Canvasback",
                             "Branta bernicla_Brant" = "https://en.wikipedia.org/wiki/Brant",
                             "Branta canadensis_Canada Goose" = "https://en.wikipedia.org/wiki/Canada_goose",
                             "Branta hutchinsii_Cackling Goose" = "https://en.wikipedia.org/wiki/Cackling_goose",
                             "Branta sandvicensis_Hawaiian Goose" = "https://en.wikipedia.org/wiki/Hawaiian_goose",
                             "Bubulcus ibis_Cattle Egret" = "https://en.wikipedia.org/wiki/Cattle_egret",
                             "Bucephala albeola_Bufflehead" = "https://en.wikipedia.org/wiki/Bufflehead",
                             "Bulweria bulwerii_Bulwer's Petrel" = "https://en.wikipedia.org/wiki/Bulwer%27s_petrel",
                             "Buteo solitarius_Hawaiian Hawk" = "https://en.wikipedia.org/wiki/Hawaiian_hawk",
                             "Calidris acuminata_Sharp-tailed Sandpiper" = "https://en.wikipedia.org/wiki/Sharp-tailed_sandpiper",
                             "Calidris alba_Sanderling" = "https://en.wikipedia.org/wiki/Sanderling",
                             "Calidris alpina_Dunlin" = "https://en.wikipedia.org/wiki/Dunlin",
                             "Calidris mauri_Western Sandpiper" = "https://en.wikipedia.org/wiki/Western_sandpiper",
                             "Calidris melanotos_Pectoral Sandpiper" = "https://en.wikipedia.org/wiki/Pectoral_sandpiper",
                             "Calidris minutilla_Least Sandpiper" = "https://en.wikipedia.org/wiki/Least_sandpiper",
                             "Calidris pugnax_Ruff" = "https://en.wikipedia.org/wiki/Ruff",
                             "Calidris subruficollis_Buff-breasted Sandpiper" = "https://en.wikipedia.org/wiki/Buff-breasted_sandpiper",
                             "Callipepla californica_California Quail" = "https://en.wikipedia.org/wiki/California_quail",
                             "Callipepla gambelii_Gambel's Quail" = "https://en.wikipedia.org/wiki/Gambel%27s_quail",
                             "Cardinalis cardinalis_Northern Cardinal" = "https://en.wikipedia.org/wiki/Northern_cardinal",
                             "Charadrius semipalmatus_Semipalmated Plover" = "https://en.wikipedia.org/wiki/Semipalmated_plover",
                             "Chasiempis sandwichensis_Hawaii Elepaio" = "https://en.wikipedia.org/wiki/Hawaii_Elepaio",
                             "Chlorodrepanis virens_Hawaii Amakihi" = "https://en.wikipedia.org/wiki/Hawaii_Amakihi",
                             "Chroicocephalus philadelphia_Bonaparte's Gull" = "https://en.wikipedia.org/wiki/Bonaparte%27s_Gull",
                             "Chrysolophus pictus_Golden Pheasant" = "https://en.wikipedia.org/wiki/Golden_Pheasant",
                             "Circus hudsonius_Northern Harrier" = "https://en.wikipedia.org/wiki/Northern_Harrier",
                             "Columba livia_Rock Pigeon" = "https://en.wikipedia.org/wiki/Rock_Pigeon",
                             "Corvus hawaiiensis_Hawaiian Crow" = "https://en.wikipedia.org/wiki/Hawaiian_Crow",
                             "Coturnix japonica_Japanese Quail" = "https://en.wikipedia.org/wiki/Japanese_Quail",
                             "Crithagra mozambica_Yellow-fronted Canary" = "https://en.wikipedia.org/wiki/Yellow-fronted_Canary",
                             "Cyanoliseus patagonus_Burrowing Parakeet" = "https://en.wikipedia.org/wiki/Burrowing_Parakeet",
                             "Drepanis coccinea_Iiwi" = "https://en.wikipedia.org/wiki/Iiwi",
                             "Estrilda astrild_Common Waxbill" = "https://en.wikipedia.org/wiki/Common_Waxbill",
                             "Euodice cantans_African Silverbill" = "https://en.wikipedia.org/wiki/African_Silverbill",
                             "Falco columbarius_Merlin" = "https://en.wikipedia.org/wiki/Merlin_(bird)",
                             "Falco peregrinus_Peregrine Falcon" = "https://en.wikipedia.org/wiki/Peregrine_Falcon",
                             "Francolinus francolinus_Black Francolin" = "https://en.wikipedia.org/wiki/Black_Francolin",
                             "Fregata minor_Great Frigatebird" = "https://en.wikipedia.org/wiki/Great_Frigatebird",
                             "Fulica alai_Hawaiian Coot" = "https://en.wikipedia.org/wiki/Hawaiian_Coot",
                             "Gallinula galeata_Common Gallinule" = "https://en.wikipedia.org/wiki/Common_Gallinule",
                             "Gallus gallus_Red Junglefowl" = "https://en.wikipedia.org/wiki/Red_Junglefowl",
                             "Garrulax canorus_Chinese Hwamei" = "https://en.wikipedia.org/wiki/Chinese_Hwamei",
                             "Geopelia striata_Zebra Dove" = "https://en.wikipedia.org/wiki/Zebra_Dove",
                             "Glaucestrilda caerulescens_Lavender Waxbill" = "https://en.wikipedia.org/wiki/Lavender_Waxbill",
                             "Gygis alba_White Tern" = "https://en.wikipedia.org/wiki/White_Tern",
                             "Haemorhous mexicanus_House Finch" = "https://en.wikipedia.org/wiki/House_Finch",
                             "Hemignathus wilsoni_Akiapolaau" = "https://en.wikipedia.org/wiki/Akiapolaau",
                             "Himantopus mexicanus_Black-necked Stilt" = "https://en.wikipedia.org/wiki/Black-necked_Stilt",
                             "Himatione sanguinea_Apapane" = "https://en.wikipedia.org/wiki/Apapane",
                             "Horornis diphone_Japanese Bush Warbler" = "https://en.wikipedia.org/wiki/Japanese_Bush_Warbler",
                             "Hydrobates castro_Band-rumped Storm-Petrel" = "https://en.wikipedia.org/wiki/Band-rumped_Storm-Petrel",
                             "Hydrobates leucorhous_Leach's Storm-Petrel" = "https://en.wikipedia.org/wiki/Leach%27s_Storm-Petrel",
                             "Hydroprogne caspia_Caspian Tern" = "https://en.wikipedia.org/wiki/Caspian_Tern",
                             "Larosterna inca_Inca Tern" = "https://en.wikipedia.org/wiki/Inca_Tern",
                             "Larus delawarensis_Ring-billed Gull" = "https://en.wikipedia.org/wiki/Ring-billed_Gull",
                             "Larus glaucescens_Glaucous-winged Gull" = "https://en.wikipedia.org/wiki/Glaucous-winged_Gull",
                             "Leiothrix lutea_Red-billed Leiothrix" = "https://en.wikipedia.org/wiki/Red-billed_Leiothrix",
                             "Leucophaeus atricilla_Laughing Gull" = "https://en.wikipedia.org/wiki/Laughing_Gull",
                             "Leucophaeus pipixcan_Franklin's Gull" = "https://en.wikipedia.org/wiki/Franklin%27s_Gull",
                             "Limnodromus scolopaceus_Long-billed Dowitcher" = "https://en.wikipedia.org/wiki/Long-billed_Dowitcher",
                             "Limosa haemastica_Hudsonian Godwit" = "https://en.wikipedia.org/wiki/Hudsonian_Godwit",
                             "Lonchura atricapilla_Chestnut Munia" = "https://en.wikipedia.org/wiki/Chestnut_Munia",
                             "Lonchura punctulata_Scaly-breasted Munia" = "https://en.wikipedia.org/wiki/Scaly-breasted_Munia",
                             "Lophodytes cucullatus_Hooded Merganser" = "https://en.wikipedia.org/wiki/Hooded_Merganser",
                             "Lophura leucomelanos_Kalij Pheasant" = "https://en.wikipedia.org/wiki/Kalij_Pheasant",
                             "Loxioides bailleui_Palila" = "https://en.wikipedia.org/wiki/Palila",
                             "Loxops caeruleirostris_Akekee" = "https://en.wikipedia.org/wiki/Akekee",
                             "Loxops coccineus_Hawaii Akepa" = "https://en.wikipedia.org/wiki/Hawaii_Akepa",
                             "Loxops mana_Hawaii Creeper" = "https://en.wikipedia.org/wiki/Hawaii_Creeper",
                             "Mareca americana_American Wigeon" = "https://en.wikipedia.org/wiki/American_Wigeon",
                             "Mareca penelope_Eurasian Wigeon" = "https://en.wikipedia.org/wiki/Eurasian_Wigeon",
                             "Mareca strepera_Gadwall" = "https://en.wikipedia.org/wiki/Gadwall",
                             "Megaceryle alcyon_Belted Kingfisher" = "https://en.wikipedia.org/wiki/Belted_Kingfisher",
                             "Meleagris gallopavo_Wild Turkey" = "https://en.wikipedia.org/wiki/Wild_Turkey",
                             "Mimus polyglottos_Northern Mockingbird" = "https://en.wikipedia.org/wiki/Northern_Mockingbird",
                             "Myadestes obscurus_Omao" = "https://en.wikipedia.org/wiki/Omao",
                             "Myadestes palmeri_Puaiohi" = "https://en.wikipedia.org/wiki/Puaiohi",
                             "Numenius tahitiensis_Bristle-thighed Curlew" = "https://en.wikipedia.org/wiki/Bristle-thighed_Curlew",
                             "Nycticorax nycticorax_Black-crowned Night-Heron" = "https://en.wikipedia.org/wiki/Black-crowned_Night-Heron",
                             "Onychoprion fuscatus_Sooty Tern" = "https://en.wikipedia.org/wiki/Sooty_Tern",
                             "Onychoprion lunatus_Gray-backed Tern" = "https://en.wikipedia.org/wiki/Gray-backed_Tern",
                             "Oreomystis bairdi_Akikiki" = "https://en.wikipedia.org/wiki/Akikiki",
                             "Ortygornis pondicerianus_Gray Francolin" = "https://en.wikipedia.org/wiki/Gray_Francolin",
                             "Padda oryzivora_Java Sparrow" = "https://en.wikipedia.org/wiki/Java_Sparrow",
                             "Palmeria dolei_Akohekohe" = "https://en.wikipedia.org/wiki/Akohekohe",
                             "Pandion haliaetus_Osprey" = "https://en.wikipedia.org/wiki/Osprey",
                             "Paroaria capitata_Yellow-billed Cardinal" = "https://en.wikipedia.org/wiki/Yellow-billed_Cardinal",
                             "Paroaria coronata_Red-crested Cardinal" = "https://en.wikipedia.org/wiki/Red-crested_Cardinal",
                             "Paroreomyza montana_Maui Alauahio" = "https://en.wikipedia.org/wiki/Maui_Alauahio",
                             "Passer domesticus_House Sparrow" = "https://en.wikipedia.org/wiki/House_Sparrow",
                             "Pavo cristatus_Indian Peafowl" = "https://en.wikipedia.org/wiki/Indian_Peafowl",
                             "Phaethon lepturus_White-tailed Tropicbird" = "https://en.wikipedia.org/wiki/White-tailed_Tropicbird",
                             "Phaethon rubricauda_Red-tailed Tropicbird" = "https://en.wikipedia.org/wiki/Red-tailed_Tropicbird",
                             "Phalaropus fulicarius_Red Phalarope" = "https://en.wikipedia.org/wiki/Red_Phalarope",
                             "Phasianus colchicus_Ring-necked Pheasant" = "https://en.wikipedia.org/wiki/Ring-necked_Pheasant",
                             "Phoebastria immutabilis_Laysan Albatross" = "https://en.wikipedia.org/wiki/Laysan_Albatross",
                             "Phoebastria nigripes_Black-footed Albatross" = "https://en.wikipedia.org/wiki/Black-footed_Albatross",
                             "Plegadis chihi_White-faced Ibis" = "https://en.wikipedia.org/wiki/White-faced_Ibis",
                             "Pluvialis fulva_Pacific Golden-Plover" = "https://en.wikipedia.org/wiki/Pacific_Golden-Plover",
                             "Pluvialis squatarola_Black-bellied Plover" = "https://en.wikipedia.org/wiki/Black-bellied_Plover",
                             "Podilymbus podiceps_Pied-billed Grebe" = "https://en.wikipedia.org/wiki/Pied-billed_Grebe",
                             "Porzana carolina_Sora" = "https://en.wikipedia.org/wiki/Sora_(bird)",
                             "Pseudonestor xanthophrys_Maui Parrotbill" = "https://en.wikipedia.org/wiki/Maui_Parrotbill",
                             "Psittacara erythrogenys_Red-masked Parakeet" = "https://en.wikipedia.org/wiki/Red-masked_Parakeet",
                             "Psittacara mitratus_Mitred Parakeet" = "https://en.wikipedia.org/wiki/Mitred_Parakeet",
                             "Psittacula krameri_Rose-ringed Parakeet" = "https://en.wikipedia.org/wiki/Rose-ringed_Parakeet",
                             "Pternistis erckelii_Erckel's Francolin" = "https://en.wikipedia.org/wiki/Erckel%27s_Francolin",
                             "Pterocles exustus_Chestnut-bellied Sandgrouse" = "https://en.wikipedia.org/wiki/Chestnut-bellied_Sandgrouse",
                             "Pterodroma cookii_Cook's Petrel" = "https://en.wikipedia.org/wiki/Cook%27s_Petrel",
                             "Pterodroma externa_Juan Fernandez Petrel" = "https://en.wikipedia.org/wiki/Juan_Fernandez_Petrel",
                             "Pterodroma inexpectata_Mottled Petrel" = "https://en.wikipedia.org/wiki/Mottled_Petrel",
                             "Pterodroma neglecta_Kermadec Petrel" = "https://en.wikipedia.org/wiki/Kermadec_Petrel",
                             "Pterodroma nigripennis_Black-winged Petrel" = "https://en.wikipedia.org/wiki/Black-winged_Petrel",
                             "Pterodroma sandwichensis_Hawaiian Petrel" = "https://en.wikipedia.org/wiki/Hawaiian_Petrel",
                             "Puffinus nativitatis_Christmas Shearwater" = "https://en.wikipedia.org/wiki/Christmas_Shearwater",
                             "Puffinus newelli_Newell's Shearwater" = "https://en.wikipedia.org/wiki/Newell%27s_Shearwater",
                             "Sicalis flaveola_Saffron Finch" = "https://en.wikipedia.org/wiki/Saffron_Finch",
                             "Spatula clypeata_Northern Shoveler" = "https://en.wikipedia.org/wiki/Northern_Shoveler",
                             "Spatula cyanoptera_Cinnamon Teal" = "https://en.wikipedia.org/wiki/Cinnamon_Teal",
                             "Spatula discors_Blue-winged Teal" = "https://en.wikipedia.org/wiki/Blue-winged_Teal",
                             "Stercorarius longicaudus_Long-tailed Jaeger" = "https://en.wikipedia.org/wiki/Long-tailed_Jaeger",
                             "Stercorarius maccormicki_South Polar Skua" = "https://en.wikipedia.org/wiki/South_Polar_Skua",
                             "Stercorarius parasiticus_Parasitic Jaeger" = "https://en.wikipedia.org/wiki/Parasitic_Jaeger",
                             "Stercorarius pomarinus_Pomarine Jaeger" = "https://en.wikipedia.org/wiki/Pomarine_Jaeger",
                             "Sterna paradisaea_Arctic Tern" = "https://en.wikipedia.org/wiki/Arctic_Tern",
                             "Sternula antillarum_Least Tern" = "https://en.wikipedia.org/wiki/Least_Tern",
                             "Streptopelia chinensis_Spotted Dove" = "https://en.wikipedia.org/wiki/Spotted_Dove",
                             "Sturnella neglecta_Western Meadowlark" = "https://en.wikipedia.org/wiki/Western_Meadowlark",
                             "Sula dactylatra_Masked Booby" = "https://en.wikipedia.org/wiki/Masked_Booby",
                             "Sula leucogaster_Brown Booby" = "https://en.wikipedia.org/wiki/Brown_Booby",
                             "Sula sula_Red-footed Booby" = "https://en.wikipedia.org/wiki/Red-footed_Booby",
                             "Tringa flavipes_Lesser Yellowlegs" = "https://en.wikipedia.org/wiki/Lesser_Yellowlegs",
                             "Tringa incana_Wandering Tattler" = "https://en.wikipedia.org/wiki/Wandering_Tattler",
                             "Tyto alba_Barn Owl" = "https://en.wikipedia.org/wiki/Barn_Owl",
                             "Zenaida macroura_Mourning Dove" = "https://en.wikipedia.org/wiki/Mourning_Dove",
                             "Zosterops japonicus_Warbling White-eye" = "https://en.wikipedia.org/wiki/Warbling_White-eye",
                             "DefaultLink" = "https://en.wikipedia.org/wiki/Main_Page"  # Default link if not found
      )
      tags$a(href = selectedLink, "Wikipedia-Seite öffnen")
    } else {
      "Wählen Sie einen Vogel aus und klicken Sie auf 'Wikipedia-Seite öffnen'."
    }
  })
}

# App erstellen
shinyApp(ui, server)
